buttons
js-tasks-ru/htmlcss-20210610_eresha pull request #3
Opened 2021-06-16 16:04 UTC by eresha1

2021-06-16 16:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 16:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 17:01 UTC, GSemikozov requested changes

2021-06-16 17:01 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
а высота кнопки при этом точно будет соответствовать макету?

2021-06-16 17:01 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 182px;
ширину советую не фиксировать так жестко, пусть просто растягивается по внутреннему содержимому, а если надо растянуть по родителю - можно добавить модификатор `.button_full_width { widdth: 100%; }`

2021-06-16 17:01 UTC, GSemikozov commented on 03-lection1/01-button/page.css
> +  width: 380px;
а почему такой маленький?)

2021-06-17 15:20 UTC, eresha1 commented on 03-lection1/01-button/button.css
> +  padding: 15px;
Поправила

2021-06-17 15:27 UTC, eresha1 commented on 03-lection1/01-button/button.css
> +  width: 182px;
А если ширину фиксировать через min-width: 182px? (чтобы кнопки визуально были по ширине одинаковые)

2021-06-17 15:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-19 18:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 182px;
это как я сказал лучше через модификатор который будет растягивать по родителю, и соответственно кнопки вставить в грид, через который мы и определим равные колонки в которые будут встраиваться кнопки)

2021-06-21 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-21 09:31 UTC, eresha1 commented on 03-lection1/01-button/button.css
> +  width: 182px;
Поправила

2021-06-22 12:18 UTC, GSemikozov approved these changes

2021-06-22 12:18 UTC, merged