4-module-1-task
js-tasks-ru/htmlcss-20210610_eresha pull request #5
Opened 2021-06-21 16:59 UTC by eresha1

2021-06-21 17:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-22 06:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-22 12:21 UTC, GSemikozov requested changes

2021-06-22 12:21 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <p class="histogram__bar-item histogram__bar-item_01" style="height: 50px"></p>
нужно выбрать 1 из 2 способов задать высоту столбцу - либо модификатор `histogram__bar-item_01` либо инлайнить через style

2021-06-22 13:32 UTC, eresha1 commented on 04-lection2/01-histogram/index.html
> +                <p class="histogram__bar-item histogram__bar-item_01" style="height: 50px"></p>
поправила

2021-06-23 19:57 UTC, GSemikozov requested changes

2021-06-23 19:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  opacity: 0.8;
здесь это лишнее (возможно, актуально для тайтла.. но точно не для всего хедера ;))

2021-06-23 19:57 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin: 0;
отступы этому элементу не задавали, поэтому и обнулять их не надо)

2021-06-24 10:36 UTC, eresha1 commented on 04-lection2/01-histogram/histogram.css
> +  margin: 0;
У меня столбцы гистограммы были заданы <p></p> (отсюда и margin)
Поправила на div, убрала margin

2021-06-24 10:36 UTC, eresha1 commented on 04-lection2/01-histogram/histogram.css
> +  opacity: 0.8;
поправила

2021-06-24 10:47 UTC, GSemikozov approved these changes

2021-06-24 10:47 UTC, merged